### ISSUE TITLE
apt下载PlatON版本，输入0.7.4，会出现先安装0.7.4.1，再安装0.7.4.2，导致无法overwrite报错

### ISSUE THREAD

**Issue by alextao0224** [PlatONnetwork/GalaxyRally#14]
chmod +x platon_setup.sh && ./platon_setup.sh 0.7.4
apt安装支持正则表达式，安装0.7.4，会出现先安装0.7.4.1，再安装0.7.4.2

**Comment by alextao0224** [comment]
优化方案
1、文档里面写x.x.x，公告里面制定具体版本号
2、如果用户输入0.7.4，没有输入第4位，则需要atp remove掉，然后删掉platon-node
3、再重新执行setup脚本，一定需要输入0.7、4、2
4、脚本优化，传版本变量后要去验证ppa的版本，如果不匹配就报错退出不再继续安装

**Comment by luo-dahui** [comment]
脚本已经优化，指定安装版本和ppa版本完全匹配时，进行安装，否则提示指定安装版本不存在。
