### ISSUE TITLE
platon脚本，需要有一个数据存放位置的变量自定义，在platon --datadir 后面用户自定义

### ISSUE THREAD

**Issue by alextao0224** [PlatONnetwork/GalaxyRally#17]
platon脚本，需要有一个数据存放位置的变量自定一比较好。一般生产上的系统盘不放那么大，大部分是多挂在一个数据盘存放数据的。在platon --datadir 后面用用户自定的位置比较好

脚本要修改的地方太多了，又不敢全局替换，我有点偷懒，测试网，直接把数据盘挂载到home目录下了
主网肯定不能这么做，要考虑数据盘动态扩容等一些列问题

**Comment by luo-dahui** [comment]
问题正在排查中。

**Comment by luo-dahui** [comment]
已经完成相关的脚本优化，和修改说明，参考：https://github.com/PlatONnetwork/GalaxyRally/pull/24
