### ISSUE TITLE
ATON委托的时候，翻动页面查找节点，出现闪退 

### ISSUE THREAD

**Issue by alextao0224** [PlatONnetwork/GalaxyRally#19]

**Comment by danielgogo** [comment]
### 错误内容：空指针
rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'java.lang.String java.math.BigInteger.toString()' on a null object reference at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)

### 原因分析：因为网络不好，DelegatePresenter对象中的gasPrice还没有被赋值就被使用，导致空指针。

### 解决方式：设置一个默认值
